Alias /notdienst_dev "/home/pi/blak_notdienst_dev/www"

<Directory "/home/pi/blak_notdienst_dev/www">
    Options FollowSymLinks
    AllowOverride None
    Require all granted
    Allow from all
    Header set Access-Control-Allow-Origin "*"
</Directory>

