#!/bin/bash

SCRIPT=$(realpath "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
CONFNAME=blak_notdienst
CONFFILE=$CONFNAME.conf
APACHE_CONFDIR=/etc/apache2/conf-available
APACHE_ENFCONF=/etc/apache2/conf-enabled

echo -e "\n************************"
echo -e   "* $CONFNAME Setup *"
echo -e   "************************\n"

if [ $(id -u) -ne 0 ]; then
	echo -e "Script must be run as root. Try 'sudo $0'\n"
	exit 1
fi

case $1 in
	install)
		if [ -h "$APACHE_CONFDIR/$CONFFILE" ]; then
			echo "$CONFFILE already exists as symbolic link in $APACHE_CONFDIR !"
			echo "So it seems to be installed already. Use remove or force-install option"
			exit 1
		fi
		
		sudo ln -s $SCRIPTPATH/$CONFFILE $APACHE_CONFDIR/
		chmod 755 $APACHE_CONFDIR/$CONFFILE
		
		if [ ! -h "$APACHE_CONFDIR/$CONFFILE" ]; then
			echo "ERROR: Could not create a symbolic link!"
			exit 1
		fi
		
		echo "Successfully installed!"
		echo "To activate the new configuration, you need to run:"
		echo "  sudo a2enconf $CONFNAME"
		echo "and then"
		echo "  sudo systemctl reload apache2" 

	;;
	
	remove)
		if [ -h "$APACHE_ENFCONF/$CONFFILE" ]; then
			echo "$CONFNAME seems still to be activated"
			echo "You have to disable it first:"
			echo "  sudo a2disconf $CONFNAME"
			exit 1
		fi
		
		if [ ! -h "$APACHE_CONFDIR/$CONFFILE" ]; then
			echo "Cannot ind $CONFFILE linked in $APACHE_CONFDIR !"
			echo "So it seems not to be installed at all."			
			exit 1
		fi
	
		unlink $APACHE_CONFDIR/$CONFFILE
		
			
		if [ ! -h "$APACHE_CONFDIR/$CONFFILE" ]; then
			echo "ERROR: Could not remove link script from $APACHE_CONFDIR/$CONFFILE !"
		fi
	;;
	
	*)
		echo -e "Usage: $0 {install|remove}\n"
		exit 1
	;;
	
esac

echo -e "** Finished $CONFNAME Setup! **\n"